name: simple-cipher

dependencies:
  - base

library:
  exposed-modules: Cipher
  source-dirs: src
  dependencies:
    - random
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - simple-cipher
      - hspec
